### PR TITLE
Add classifier client module and tests

### PR DESCRIPTION
**Pull request by kraih**
This makes the classifier task testable with a mock server.

### CODE REVIEW

**Comment by kraih** [comment]
The user agent connecting to the classifier now also uses keep-alive for better performance.

**Comment by kraih** [comment]
The text to be classified should probably not be sent as a JSON string, that's a bit weird and not very future proof.

**Comment by coolo** [comment]
yeah, but I was done hacking the python thing in less than an hour :)

**Comment by kraih** [comment]
Making it a JSON object and decoding that in the python server probably wouldn't have taken much longer. 😉

**Pull request merged**
