### PR TITLE
Add background task to classify snippets

### PR DESCRIPTION
**Pull request by coolo**
There is only a command yet to trigger it. This would be one of the tasks that are scheduled often, but locked

### CODE REVIEW

**Comment by coolo** [comment]
No good idea how to test this - creating a mini mojo server in tests?

**Comment by kraih** [comment]
Yes, you can factor out the client into a new module and store the client instance in an app property. Then test it like the [OBS client](https://github.com/openSUSE/cavil/blob/255f23792a28affe6df759c4fc78fc72ce068ecd/t/obs.t#L384).

**Comment by coolo** [comment]
Before filtering by Classifier:
screencapture-f102-suse-de-4000-reviews-details-6-2019-07-08-13_51_10

After filtering:
screencapture-f102-suse-de-4000-reviews-details-6-2019-07-08-13_52_35

The changes entries are sniped out. Files to consider shrinked from 13 to 5.

**Comment by kraih** [comment]
Neat, the classifier should probably optional though.

**Comment by kraih** [comment]
Especially as long as it's not open source.

**Comment by coolo** [comment]
For now it *is* optional - if you don't call the classify job, nothing is classified and as such nothing taking into account.

And the classifier *is* open source: MIT - https://github.com/coolo/Character-level-cnn-pytorch

**Comment by coolo** [comment]
(even containing the trained model)

**Pull request merged**
