### PR TITLE
Expand sources on demand 

### PR DESCRIPTION
**Pull request by coolo**
Always show the full list of files, but only read the files we actually show. Do the rest by ajax (by having a file specific report function)

### CODE REVIEW

**Comment by kraih** [comment]
Does this really work with Firefox and Libreoffice? I'm a little sceptical.

**Comment by coolo** [comment]
What worries you? the generated size of HTML or the runtime? I tested with kernel-source - there it goes up 10s to 19s, so noticably - but IMO acceptable price.

I'll test libreoffice

**Comment by coolo** [comment]
libreoffice report renders in 28s, firefox in 56s. Not great, but it's pretty big packages.

**Comment by kraih** [comment]
Both, i vaguely remember trying the same at some point and it wasn't good enough then. But who knows, maybe browsers got more efficient. 😆

**Comment by coolo** [comment]
memory usage goes up to 1.2G while rendering FF.

**Comment by coolo** [comment]
(on the server)

**Comment by coolo** [comment]
With that last commit, firefox report renders in 3.6s

**Comment by coolo** [comment]
(3.0s if we avoid `url_for('file_view'`))

**Comment by coolo** [comment]
this time I wont' promise to write test cases - it's a mess :)

**Pull request merged**
